---
# The settings in this file override Basic WordPress Vagrant project's defaults.


# ----- WordPress Version -----
# 
# Install a different version of WordPress
# Basic-WordPress-Vagrant can install any past or future version of WordPress
# available from the WordPress Release Archive -- even Nightly builds.
# https://wordpress.org/download/release-archive/
#
#     Remember, the only version of WordPress considered "safe to use"
#     is the latest release.
#
# Uncomment any of the following lines to change your WordPress version
# wp_download: https://wordpress.org/latest.zip  # Current release (default)
# wp_download: https://wordpress.org/nightly-builds/wordpress-latest.zip  # Latest nightly build
# wp_download: https://wordpress.org/wordpress-4.7-beta1.zip  # Version 4.7, First beta
# wp_download: https://wordpress.org/wordpress-4.6.1.zip  Version 4.6.1
# wp_download: https://wordpress.org/wordpress-4.1.8.zip  Version 4.1.8


# ----- Auto-install plugins -----
#
# Attempt installation of missing plugins
# Uncomment to skip installing missing plugins
# install_plugins: no


# ----- WordPress Installation Directory -----
#
# Relocate WordPress to a subdirectory
# Enter a subdirectory relative to your web root (/vagrant)
# Setting wp_dir will not update your webroot, so you will need to navigate down to your WP install
# wp_dir: wordpress


# ----- WP-Content Location -----
#
# Rename the wp-content directory. Roots.io style installs rename wp-content to '/app'.
# This is an advanced setting, you will need to manually populate the alternate wp-content
# directory. The path will be created if it doesn't exist.
# wp_content: app
 
 
# ----- xDebug -----
#
# Use this to disable xDebug in PHP. Defaults to 'yes'
# enable_xdebug: no
