---

- name: Create Database
  mysql_db: name={{ wp_config.db_name }} state=present

- name: Find MySQL dumpfiles
  command: find /vagrant -type d -name "plugins" -prune -o -name "*.sql" -print
  register: dumpfiles
  
- name: Found dumpfile
  debug: "msg='Populating database from {{ dumpfiles.stdout_lines | last | relpath(\'/vagrant\')}}'"

- name: Load dumpfile into the new database
  mysql_db:
    name={{ wp_config.db_name }}
    state=import
    target={{ dumpfiles.stdout_lines | last }}
  when: dumpfiles.stdout_lines
