---

- name: Make sure /site directory exists
  connection: local
  become: no
  file: 
    path: '{{ vagrant_cwd }}/site'
    state: directory 
    mode: 0755

- name: Download and extract WordPress
  connection: local
  become: no
  unarchive: 
    src: "{{ wp_download | default('https://wordpress.org/latest.zip', true) }}"
    dest: /tmp/
    copy: no

# - name: Download fresh copy of WordPress
#   connection: local
#   become: no
#   get_url: 
#     url: "{{ wp_download | default('https://wordpress.org/latest.zip', true) }}"
#     dest: /tmp/wordpress.zip
#     force: yes

# - name: Decompress WordPress archive
#   connection: local
#   become: no
#   unarchive: 
#     src: /tmp/wordpress.zip
#     dest: /tmp/
#     copy: no
    
- name: Sync fresh WordPress onto /site
  connection: local
  become: no
  synchronize: src=/tmp/wordpress/ dest={{ vagrant_cwd }}/site/

- name: Get WP Engine .gitignore file (if there isn't one already)
  get_url: 
    url: 'https://gist.githubusercontent.com/joemaller/4f7518e0d04a82a3ca16/raw/'
    dest: '/vagrant/site/.gitignore'

- name: Flywheel cleanup
  file: path=/vagrant/site/{{ item }} state=absent
  with_items: 
    - flywheel-config

- name: WP Engine cleanup
  file: path=/vagrant/site/wp-content/{{ item }} state=absent
  with_items: 
    - advanced-cache.php
    - mu-plugins/force-strong-passwords
    - mu-plugins/mu-plugin.php
    - mu-plugins/slt-force-strong-passwords.php
    - mu-plugins/stop-long-comments.php
    - mu-plugins/wpengine-common
    - plugins/hyperdb
    - plugins/hyperdb-1-1
