---

- import_tasks: install.yml
- import_tasks: host-specific-cleanup.yml
- import_tasks: wp-config.yml
- import_tasks: database.yml
- import_tasks: wp-cli.yml
  when: (dumpfiles is defined) and dumpfiles.stdout_lines
