---


# - debug: var=vagrant_local_webroot
- debug: var=vagrant_local_wp_root

- name: Create download cache directory
  connection: local
  become: no
  file:
    path: /tmp/wordpress-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}
    state: directory
  register: wp_download_tmp

- name: Clean remote WordPress Source directory
  file:
    path: /tmp/wordpress_BOO
    state: absent
  register: wp_src_dir

- name: Create remote expansion directory
  file:
    path: '{{ wp_src_dir.path }}'
    state: directory
    mode: 0777

- name: Download WordPress archive
  connection: local
  become: no
  get_url: 
    url: "{{ wp_download | default('https://wordpress.org/latest.zip', true) }}"
    dest: '{{ wp_download_tmp.path }}/wordpress_archive.zip'
  register: wp_archive

- name: Extract WordPress archive on remote host
  become: no
  unarchive: 
    src: '{{ wp_archive.dest }}'
    dest: '{{ wp_src_dir.path }}'
  register: wp_files
