---

- hosts: all
  sudo: yes

  vars_files:
    - defaults/main.yml
    - vars/wordpress.yml

  pre_tasks:
    - debug: var=hostvars
      sudo: no
    - debug: var=vars
      sudo: no

  roles:
    - wordpress
