---

- hosts: all
  sudo: yes

  vars_files:
    - defaults/main.yml
    - vars/wordpress.yml

  roles: 
    - wordpress
  #   - php
  #   - php5-xdebug
  tasks:     
    # for anible 2.0, whenever that ships...
    # - name: find sql dumpfiles
    #   find: paths="{ item }" patterns="*.sql"
    #   register: dumpfile
    #   with_items:
    #   - /vagrant/site/wp-content/
    #   - /vagrant/site/
    #   - /vagrant/

    # - name: find sql dumpfiles
    #   shell: "find {{ ansible_env.PWD }} -iregex *.sql"
    #   register: dumpfile
      # with_items:
      # - /vagrant/site/wp-content/
      # - /vagrant/site/
      # - /vagrant/
      
    # - debug: var=vars
    # - debug: var=hostvars

    
    # - name: check for mysql.sql dumpfile
    #   stat: path=/vagrant/site/mysql.sql
    #   register: dumpfile
      
    # - debug: var=dumpfile
    
    # - name: check for mysql.sql dumpfile
    #   stat: path=/vagrant/site/wp-content/mysql.sql
    #   register: dumpfile
      
    # - debug: var=dumpfile
    
    # - name: Local WP Download
    #   sudo: no
    #   local_action:       
    #     get_url
    #     url=https://wordpress.org/wordpress-{{ wp.version }}.tar.gz
    #     dest=/tmp/wordpress.tar.gz

    #   register: foo

    # - debug: var=foo

    # - name: Extract WordPress tar
    #   local_action:
    #     command tar -xzC /tmp/wordpress --strip
    #       src=/tmp/wordpress.tar.gz
    #       dest=/tmp/site/
    #       copy=no

    
            